name: Compile Action
on: [push]
jobs:
  build-code:
    runs-on: [self-hosted]
    steps:
      - run: echo "Job running for branch ${{ github.ref }} in repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile project
        run: |
          python3 -m compileall