name: Compile Action
on: [push]
jobs:
  build-code:
    runs-on: [self-hosted]
    steps:
      - run: echo "Job running for branch ${{ github.ref }} in repository ${{ github.repository }}."
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Run Tests
        run: cd CI && chmod +x RunTests.sh && ./RunTests.sh